### ISSUE TITLE
Does not work on Node v10.13.0

### ISSUE THREAD

**Issue by mcebular** [kumuluz/kumuluzee-nodejs-discovery#1]
Running kumuluzee-nodejs-discovery results in a crash with the following error:
```
.../kumuluzee-nodejs-samples/kumuluzee-nodejs-discovery/node_modules/deasync/index.js:65
                process._tickDomainCallback();
                        ^

TypeError: process._tickDomainCallback is not a function
    at Function.module.exports.runLoopOnce (.../kumuluzee-nodejs-samples/kumuluzee-nodejs-discovery/node_modules/deasync/index.js:65:11)
```

Node version: v10.13.0
NPM version: 6.4.1

I investigated the cause of the error, it happens in deasync module, which is a dependency of [node-etcd](https://github.com/stianeikeland/node-etcd) module.
This can be fixed by bumping node-etcd dependency to a more recent version in _package.json_ (at least to 6.0.0, where this problem is fixed as noted in [node-etcd changelog](https://github.com/stianeikeland/node-etcd#changes).

Note: I was running the discovery sample from [kumuluzee-nodejs-samples](https://github.com/kumuluz/kumuluzee-nodejs-samples)

**Comment by Jamsek-m** [comment]
Hi,
Thank you for notifying us. The problem should now be fixed in [version 1.1.0](https://github.com/kumuluz/kumuluzee-nodejs-discovery/releases/tag/1.1.0) where node-etcd was updated to latest version. Samples have been updated accordingly.

Please re-open issue if the error still persists.
